export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_CHARACTERS_PENDING = 'REQUEST_CHARACTERS_PENDING';
export const REQUEST_CHARACTERS_SUCCESS = 'REQUEST_CHARACTERS_SUCCESS';
export const REQUEST_CHARACTERS_FAILED = 'REQUEST_CHARACTERS_FAILED';

